config/routes.rb
Rails.application.routes.draw do
  resources :batches
  resources :publications
  devise_for :users
  resources :courses
  resources :students
  resources :instructors

   root 'courses#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @course = Course.new
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @student = Student.new
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
        format.js
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :instructor_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<tr id="row_<%= @course.id %>">
             <td><%= link_to @course.name, @course %></td>
             <td><%= @course.description %></td>
             <td><%= @course.instructor.name %></td>
            
             <% if user_signed_in? %>
               <% if can? :update, @course %>
                 <td>
                   <%= link_to edit_course_path(@course) do  %>
                    <i class="glyphicon glyphicon-pencil"></i>
                   <% end %>
                 
               <% end %>
               <% if can? :destroy, @course %>
                 
                  <%= link_to @course, method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
                    <i class="glyphicon glyphicon-trash"></i>
                  <% end %>
                  </td>
               <% end %>
             <% end %>
           </tr>

app/views/courses/_errors.html.erb
 <div class="alert alert-danger">
  <h4><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h4>
  <ul>
    <% @course.errors.full_messages.each do |message| %>
       <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/courses/_form.html.erb
<%= form_for(@course, remote: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="from-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :instructor_id %><br>
    <%= f.collection_select :instructor_id, Instructor.all, :id, :name, { prompt: "Select Instructor"} , { class: "form-control"} %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/courses/create.js.erb
<% if @course.errors.any? %>
	$('#error').html("<%= escape_javascript render('errors')%>");
<% else %>
	$('#error').hide();
	$('#courseList').append("<%= escape_javascript render('course') %>");
	$('#new_course')[0].reset();
<% end %>

app/views/courses/destroy.js.erb
$('#alert').html("<div class='alert alert-danger'> Successfully deleted Category</div>");
$('#row_<%= @course.id %>').fadeOut();
$('#alert').fadeOut(5000);

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="page-header">
      <h2><span class="glyphicon glyphicon-th-list"></span> Listing Courses</h2>
    </div>
     <table class="table table-striped" id="courseList">
       <thead>
         <tr>
           <th>Name</th>
           <th>Description</th>
           <th>Instructor</th>
           <th>Students Enrolled</th>
           <th></th>
         </tr>
       </thead>

       <tbody>
         <% @courses.each do |course| %>
           <tr id="row_<%= course.id %>">
             <td><%= link_to course.name, course %></td>
             <td><%= course.description %></td>
             <td><%= course.instructor.name %></td>
             <td><%= course.students.length %></td>
            
             <% if user_signed_in? %>
               <% if can? :update, course %>
                 <td>
                   <%= link_to edit_course_path(course) do  %>
                    <i class="glyphicon glyphicon-pencil"></i>
                   <% end %>
                 
               <% end %>
               <% if can? :destroy, course %>
                 
                  <%= link_to course, method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
                    <i class="glyphicon glyphicon-trash"></i>
                  <% end %>
                  </td>
               <% end %>
             <% end %>
           </tr>
         <% end %>
       </tbody>
     </table>

  </div>

  <div class="col-md-4">
    <% if user_signed_in? && (can? :create, Course.new)  %>
      <div class="page-header">
        <h2>Add Course</h2>
      </div>
      <div id="error">
        
      </div>
       <%= render 'form' %>
    <% end %>
  </div>
</div>
<br>

<% data = {} 
  @courses.each do |course|
    data[course.name] = course.students.length
  end
%>


<% if (user_signed_in?) && (current_user.role? "admin") %>
<div class="row">
  <div class="col-md-6">
    <h5>Pie Chart</h5>
    <%= pie_chart(data) %>
  </div>
  <div class="col-md-6">
    <h5>Column Chart</h5>
    <%= column_chart(data) %>
  </div>
  <div class="col-md-6">
    <h5>Line Chart</h5>
    <%= line_chart(data) %>
  </div>
  <div class="col-md-6">
     <h5>Bar Chart</h5>
    <%= bar_chart(data) %>
  </div>
</div>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<div class="row">
	<div class="col-md-12">
		<ol class="breadcrumb">
		  <li><a href="/">Home</a></li>
		  <li><a href="/courses">Courses</a></li>
		  <li class="active"><%= @course.name %></li>
		</ol>
	</div>
</div>

<div class="row">
	<div class="col-md-8">
		<h2><%= @course.name %></h2>
		<p class="text-justify"><%= @course.description %></p>
		<p>
  		<strong>Instructor:</strong>
 				 <%= link_to @course.instructor.name, instructor_path(@course.instructor_id)%>
		</p>
		<div class="jumbotron">
 		 <h1>Limited Seats!</h1>
 			 <p>New Batch begins from 11th Jan, 2018</p>
 			 
 			  <!-- Button trigger modal -->
				<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#registrationForm">
			 	 Register
				</button>		

				<!-- Modal -->
				<div class="modal fade" id="registrationForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				  <div class="modal-dialog" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        <h4 class="modal-title" id="myModalLabel">Registration Form</h4>
				      </div>
				      <div class="modal-body">
				      	<span id="success"></span>
				      	<span id="error"></span>
				       	<%= render './students/form' %>
				      </div>
				      
				    </div>
				  </div>
				</div>
				</div>

	</div>
	<div class="col-md-4">
		<% if user_signed_in? %>
	<h2>Students Enrolled </h2>
	<% if @course.students.empty? %>
		<p> No students enrolled yet </p>
	<% else %>
		<ul>
			<% @course.students.each do |student| %>
				<li><%= link_to student.name, student_path(student.id) %> </li>
			<% end %>
		</ul>
	<% end %>
<% end %>

<% if user_signed_in? %> 
	<%= link_to 'Edit', edit_course_path(@course) %> |
<% end %>		
	</div>
</div>

<%= link_to 'Back', courses_path %>